name: Deploy Site

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List files for debug
        run: ls -R

      - name: Build Docker image
        run: docker build -t monsite:latest -f ./Dockerfile .

      - name: Save Docker image
        run: docker save monsite:latest | gzip > monsite.tar.gz

      - name: Upload built image artifact
        uses: actions/upload-artifact@v4   # <--- FIX HERE
        with:
          name: built-image
          path: monsite.tar.gz


  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Download built image
        uses: actions/download-artifact@v4   # <--- FIX HERE
        with:
          name: built-image

      - name: Load Docker image
        run: gunzip -c monsite.tar.gz | docker load

      - name: Test container
        run: |
          docker run -d -p 8081:80 --name testsite monsite:latest
          sleep 5
          curl -f http://localhost:8081
          docker stop testsite
          docker rm testsite


  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
