name: Deploy Site

permissions:
  contents: write   # <--- IMPORTANT

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List files for debug
        run: ls -R

      - name: Build Docker image
        run: docker build -t monsite:latest -f ./Dockerfile .

      - name: Test Docker container
        run: |
          docker run -d -p 8081:80 --name testsite monsite:latest
          sleep 5
          curl -f http://localhost:8081
          docker stop testsite
          docker rm testsite

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
